"""added notebooks table

Revision ID: 45631083f11f
Revises: 542ac9d582c3
Create Date: 2026-04-02 15:00:40.241028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45631083f11f"
down_revision: Union[str, Sequence[str], None] = "542ac9d582c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebooks",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notebooks_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notebooks")),
    )
    op.create_index(
        op.f("ix_notebooks_deleted_at"), "notebooks", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_notebooks_uid"), "notebooks", ["uid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notebooks_uid"), table_name="notebooks")
    op.drop_index(op.f("ix_notebooks_deleted_at"), table_name="notebooks")
    op.drop_table("notebooks")
    # ### end Alembic commands ###
